name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # 当推送以 "v" 开头的 tag 时触发

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 3: 使用 Docker Buildx 构建和推送多平台镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jontyding/informer:latest
          platforms: linux/amd64,linux/arm64
